# -*- coding: utf-8 -*-
"""Chatbot with Transformer-Based Language Model (DialoGPT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKYgrwW1BbCxeOcU-7lO2w31ebT7-_yO
"""

# ai_chatbot_dialo.py

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

def chatbot():
    print("Loading DialoGPT model...")
    tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
    model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

    chat_history_ids = None

    print("Start chatting with the bot (type 'quit' to stop):")
    while True:
        user_input = input("User: ")
        if user_input.lower() == "quit":
            break

        # Encode input and append chat history
        new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt')

        bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if chat_history_ids is not None else new_input_ids

        # Generate response
        chat_history_ids = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id)

        response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
        print(f"Bot: {response}")

if __name__ == "__main__":
    chatbot()